apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: pns # Kind uses containerd so we cannot use docker as default runtime executor