apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: code-pushed-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.14.0
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: code-pushed
      gatewayName: code-pushed-gateway
      eventName: codePushed
  subscription:
    http:
      port: 9300
  triggers:
    - template:
        name: build-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: demo-ci-
              spec:
                serviceAccountName: argo-events-sa
                entrypoint: demo-ci
                arguments:
                  parameters:
                  - name: repo
                    value: SET_FROM_PARAMETER
                  - name: revision
                    value: SET_FROM_PARAMETER
                  - name: ref
                    value: SET_FROM_PARAMETER

                templates:
                - name: demo-ci
                  steps:
                    # todo: Add git checkout step to checkout the commit referenced in the git push event
                  - - name: build
                      template: build
                      when: "'{{workflow.parameters.revision}}' != '0000000000000000000000000000000000000000'" # No commit SHA = only tag was pushed

                - name: build
                  container:
                    image: gcr.io/kaniko-project/executor:v0.15.0
                    args: ["--dockerfile=Dockerfile",
                          "--context={{workflow.parameters.repo}}#{{workflow.parameters.ref}}",
                          "--destination=docker-registry.default:5000/demo:latest",
                          "--insecure"]

      # Apply parameters at the template level.
      parameters:
        - src:
            dependencyName: code-pushed
            dataKey: body.repository.git_url
          dest: k8s.source.resource.spec.arguments.parameters.0.value
        - src:
            dependencyName: code-pushed
            dataKey: body.after # The commit SHA after push
          dest: k8s.source.resource.spec.arguments.parameters.1.value
        - src:
            dependencyName: code-pushed
            dataKey: body.ref
          dest: k8s.source.resource.spec.arguments.parameters.2.value