apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: code-pushed
spec:
  type: webhook
  webhook:
    # gateway can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    codePushed:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /pushed
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST